### ISSUE TITLE
FTBFS: DenseFieldIO.h: No such file or directory

### ISSUE THREAD

**Issue by ghisvail** [imageworks/Field3D#88]
I have refreshed the packaging with version `v1.7.1`. Compilation fails early with the following error:
```
[  4%] Building CXX object CMakeFiles/Field3D.dir/src/DenseFieldIO.cpp.o
/usr/bin/c++   -DField3D_EXPORTS -DREQUIRE_IOSTREAM -I/<<PKGBUILDDIR>>/. -I/<<PKGBUILDDIR>>/src -I/<<PKGBUILDDIR>>/export -I/usr/include/OpenEXR -I/usr/include/hdf5/serial  -g -O2 -fPIE -fstack-protector-strong -Wformat -Werror=format-security -Wall -pedantic -Wdate-time -D_FORTIFY_SOURCE=2  -fPIC   -fPIC -Wno-invalid-offsetof -o CMakeFiles/Field3D.dir/src/DenseFieldIO.cpp.o -c /<<PKGBUILDDIR>>/src/DenseFieldIO.cpp
/<<PKGBUILDDIR>>/src/DenseFieldIO.cpp:44:26: fatal error: DenseFieldIO.h: No such file or directory
compilation terminated.
```
Between `v1.6.x` and `v1.7.1`, it seems that `DenseFieldIO.h` was removed from `export`, hence the compilation error.

**Comment by magnusw** [comment]
Right, I'll need to update the CMake files. Some headers moved from export/
to include/. Thanks for spotting that.

**Comment by ghisvail** [comment]
Hi Magnus, any news on this?

**Comment by magnusw** [comment]
Hi Ghislain,

It's been a couple of crazy weeks at work. I will try to get it done
towards the end of this week.

Magnus

**Comment by ghisvail** [comment]
No pressure. I understand.

**Comment by hobbes1069** [comment]
Until Field3D is updated, the patch is trivial:

```
--- a/CMakeLists.txt
+++ b/CMakeLists.txt
@@ -64,6 +64,7 @@ FILE ( COPY export/ DESTINATION ${CMAKE_
 INCLUDE_DIRECTORIES ( . )
 INCLUDE_DIRECTORIES ( src )
 INCLUDE_DIRECTORIES ( export )
+INCLUDE_DIRECTORIES ( include )
 INCLUDE_DIRECTORIES ( ${ILMBASE_INCLUDE_DIRS} )
 INCLUDE_DIRECTORIES ( ${HDF5_INCLUDE_DIRS} )
 INCLUDE_DIRECTORIES ( ${Boost_INCLUDE_DIR} )
```

**Comment by ghisvail** [comment]
@magnusw could you confirm the patch proposed by @hobbes1069 ? Thanks.

**Comment by magnusw** [comment]
I updated the master branch last night. Let me know if you have any issues still. Closing this for now.

**Comment by ghisvail** [comment]
I used @hobbes1069 and refreshed the packaging. I confirm this problem is fixed.

**Comment by ghisvail** [comment]
It is quite a mjor bug though, so you might want to consider doing another point release.
